#!/usr/bin/env node
/**
 * Turn the two ABOUT files into a module `@byollm/protocol` can ship.
 *
 * The description of record is markdown at the root of this repository,
 * because that is what people edit and review. What a surface needs is a
 * string it can render — the dashboard bundles, the site is static, and
 * neither can read a file out of `node_modules` at runtime.
 *
 * So the markdown is the source and this generates the module, the same
 * arrangement `pnpm register` uses for migrations. `verify` runs it with
 * `--check`, which fails when the generated file and the markdown disagree —
 * the one-source rule enforced rather than remembered.
 *
 * It rides in the protocol package because every surface already depends on
 * it. Before this, the paragraph lived in two hand-kept copies in another
 * repository, which is the exact defect the one-source rule exists to
 * prevent, and it nearly shipped a superseded draft.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const OUT = join(ROOT, "packages/protocol/src/about.ts");
const CUT = "<!-- lede ends here.";

const full = readFileSync(join(ROOT, "ABOUT.md"), "utf8").trim();
const short = readFileSync(join(ROOT, "ABOUT-SHORT.md"), "utf8").trim();

const at = short.indexOf(CUT);
if (at === -1) {
  process.stderr.write(
    "\n  ABOUT-SHORT.md has no cut mark, so there is no lede to show on its\n" +
      "  own. Restore the `<!-- lede ends here. … -->` comment.\n\n",
  );
  process.exit(1);
}
const lede = short.slice(0, at).trim();
const tail = short
  .slice(short.indexOf("-->", at) + 3)
  .replace(/\*\*Learn more →\*\*\s*$/, "")
  .trim();

const quote = (text) => JSON.stringify(text);

const body = `// Generated by scripts/generate-about.mjs. Do not edit.
//
// The description of record is ABOUT.md and ABOUT-SHORT.md at the root of the
// byollm repository. Edit those, then run \`pnpm run about\`. \`verify\` fails
// when this file and they disagree, which is the one-source rule with teeth:
// the paragraph previously lived in hand-kept copies in another repository and
// a superseded draft nearly shipped.

/** The full description — five sections, plus why it matters. */
export const ABOUT = ${quote(full)};

/**
 * The first paragraph, which stands alone.
 *
 * What the welcome screen shows: somebody deciding whether to trust a site's
 * button needs the whole idea in one breath, not a page.
 */
export const ABOUT_SHORT_LEDE = ${quote(lede)};

/** The rest, for surfaces with room. Shown before "Learn more →". */
export const ABOUT_SHORT_TAIL = ${quote(tail)};

/** Both halves, for a surface that wants the paragraph entire. */
export const ABOUT_SHORT = \`\${ABOUT_SHORT_LEDE}\\n\\n\${ABOUT_SHORT_TAIL}\`;
`;

if (process.argv.includes("--check")) {
  let current;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // No generated file yet is drift too: the package would ship nothing
    // where the description of record should be.
    current = "";
  }
  const copies = [
    ["packages/protocol/ABOUT.md", `${full}\n`],
    ["packages/protocol/ABOUT-SHORT.md", `${short}\n`],
  ];
  const staleCopy = copies.find(([where, want]) => {
    try {
      return readFileSync(join(ROOT, where), "utf8") !== want;
    } catch {
      return true;
    }
  });
  if (current !== body || staleCopy !== undefined) {
    process.stderr.write(
      "\n  packages/protocol/src/about.ts is not what ABOUT.md and\n" +
        "  ABOUT-SHORT.md say. One of them has drifted, and a description in\n" +
        "  two states is the defect the one-source rule exists to prevent.\n" +
        "  Run `pnpm run about`.\n\n",
    );
    process.exit(1);
  }
  process.stdout.write("about: the shipped text matches the files\n");
} else {
  writeFileSync(OUT, body);
  // Shipped as markdown too, for anybody reading the package rather than
  // importing it — npm renders these, and a description you have to run a
  // bundler to read is a description most people will not read.
  writeFileSync(join(ROOT, "packages/protocol/ABOUT.md"), `${full}\n`);
  writeFileSync(join(ROOT, "packages/protocol/ABOUT-SHORT.md"), `${short}\n`);
  process.stdout.write(`wrote ${OUT} and the two markdown copies\n`);
}
